### ISSUE TITLE
Possible to export scenes from bridge as JSON for this?

### ISSUE THREAD

**Issue by realdannys** [paolotremadio/homebridge-hue-scenes#3]
I wondered - would it be possible to build fading and colour changing scenes in something like the Hue Lights app, then export them from the bridge as JSON to use with this instead (and thus trigger fading scenes in Homekit)

**Comment by realdannys** [comment]
I did export my Hue scene as a JSON and I see the formatting isn't exactly the same. I've figured out your example but how can we apply different settings to each bulb?

Can we use lightstates?

```
 "lightstates": {
		"1": {
			"on": true,
			"bri": 237,
			"xy": [0.5806, 0.3903]
		}
	}
```

**Comment by realdannys** [comment]
So lightstates isn't possible - how then can we perform different settings for each bulb in a scene? @paolotremadio

**Comment by paolotremadio** [comment]
It is possible to set any state that you would set on a scene or via `PUT /api/USERNAME/lights/ID/state`. The plugin is technically sending a put request to each light to set the state you’ve specified in the config. 

About the lightstates, please check the format of the config file: https://github.com/paolotremadio/homebridge-hue-scenes/blob/master/example.json

There’re many reasons why the config doesn’t use the same API as Hue:
- it allows you to name a light, so you can change a lightbulb without having to change each scene; you just change the definition 
- you can group multiple lights under the same name and set them to the same state
- you can set the same state to multiple lights. 

This plugin is a bit more higher level than the hue api. It does handle the complexity of mapping names to light(s) rather than being a low level “set this light id to this state”

**Comment by paolotremadio** [comment]
More details on here: https://github.com/paolotremadio/homebridge-hue-scenes/blob/master/README.md

**Comment by realdannys** [comment]
I did study the example config which is how I got my first scene working.

I understand how grouping lights works and how to apply the settings to them.

But can you give me an example where I can have one scene where I make one light (or group of lights) green and the other blue. I don’t understand how I can have more than one setting pane in a scene.

**Comment by paolotremadio** [comment]
You're right, sorry. The example was not that complete.

I've added a couple more combinations:
https://github.com/paolotremadio/homebridge-hue-scenes/blob/master/example.json

**Comment by realdannys** [comment]
Ahh I see you can have multiple settings segments and then apply them to the groups you want. Perfect! Now i'm with it. Thanks for the work!

**Comment by paolotremadio** [comment]
Exactly :) you can have many settings per scene, each targeting one or more zones. The zone can be a single light or multiple lights. That should give you extreme flexibility 👍

**Comment by realdannys** [comment]
@paolotremadio this is fantastic - i'm well into the swing of things now. I've figured out how to do blink and multiple blink too (shame you can't control it easily to repeat X amount of times, but at least I know how IFTTT were doing it now)

One thing, I wonder if you might know. I've been through all the API documentation but can't find it anywhere - someone said that you can revert the previous settings. So for instance you might have a cinema scene set that fades all the lights down and when you stop you'd want them to fade but back up to the previous settings, any idea if it's possible to do that with scenes?

At the moment I have them fade back to the scene i'm most likely going to be using (i've recreated Relax with the transition time) but if it's possible to make them revert back to whatever settings were being used before that'd be even better.

**Comment by paolotremadio** [comment]
@realdannys you will not be able to do that using this plugin. But you can do it using the Hue REST api.

It is a bit weird but this is how it works: on the API, you create a scene and add the lights to it. This scene will be the place where you store the snapshot of the settings you want to restore. Don't set `lightstates` for this scene.

Now that you have the scenes with the lights, you can do the following:
https://developers.meethue.com/develop/hue-api/4-scenes/#43_modify_scene

`
PUT /api/<username>/scenes/<id>/
{ "storelightstate": true}
`

> `storelightstate`: If set, the lightstates of the lights in the scene will be overwritten by the current state of the lights. 

Whenever you want to return to the previous settings, you just apply this scene to your group/lights :)

**Comment by realdannys** [comment]
Ah I see - so you'd have to run the storelight state first, before applying the new scene you want, so you can then recall that scene back again. 

There's perhaps another Homebridge plugin I could find that might do that - or use virtual switches with Webcore maybe, a tricky one. I like the way i'm able to control the scenes in your plugin though, but being able to revert back to a previous scene is really useful in a few situations.

**Comment by paolotremadio** [comment]
This plugin can expose switches that send specific requests when turned on or off: 
https://www.npmjs.com/package/homebridge-http-webhooks

**Comment by realdannys** [comment]
Thanks @paolotremadio - I guess that would do it. Whilst I understand the concept and the use of the API to modify the scene and then you can recall that, i'm not sure what actual lines i'd have to piece into the webhooks plugin for it work.

**Comment by realdannys** [comment]
@paolotremadio just thought i'd let you know that with your help and by learning your plugin I was able to program this with Webcore and i'm also now really comfortable with the API which is great. 

Going to use a mixture of your plugin, writing direct to the API and Hue Lights (for colours, saturation etc translation to API values) from now. Cheers!
